### ISSUE TITLE
Upgrade to FluentAssertions 5.5.0 yields: System.MissingMethodException

### ISSUE THREAD

**Issue by dstj** [fluentassertions/fluentassertions.json#27]
After upgrading FluentAssertions from `5.4.2` to `5.5.0`, the following code:

    var actualString = @"<JSON HERE>";
    var expectedString = @"<JSON HERE>";
    var actual = JsonParsingHelper.Parse(actualString);
    var expected = JsonParsingHelper.Parse(expectedString);
    actual.Should().BeEquivalentTo(expected);

produces the following error:

    System.MissingMethodException : Method not found: 'FluentAssertions.Execution.AssertionScope FluentAssertions.Execution.AssertionScope.ForCondition(Boolean)'.
       at FluentAssertions.Json.JTokenAssertions.HaveElement(String expected, String because, Object[] becauseArgs)

**Comment by franklores-ca** [comment]
any progress on this? I'm getting the same error after upgrading

**Comment by dennisdoomen** [comment]
Sorry. Forgot about the _other_ repo. Will take a look soon.

**Comment by dennisdoomen** [comment]
Hmm, looks like I've introduced a breaking change in the main library without me realizing it. 

cc @jnyrup

**Comment by jnyrup** [comment]
@dennisdoomen Probably due to https://github.com/fluentassertions/fluentassertions/pull/925

**Comment by dennisdoomen** [comment]
Yep. Trying to figure out how we can fix this.

**Comment by dennisdoomen** [comment]
If they directly use the `AssertionScope`, yes.

**Comment by dennisdoomen** [comment]
And you did mention the potential for breaking changes while you reviewed https://github.com/fluentassertions/fluentassertions/pull/925 😢

**Comment by dennisdoomen** [comment]
Should be fixed by https://github.com/fluentassertions/fluentassertions/releases/tag/5.5.3
