### ISSUE TITLE
SelectToken silently fail if token does not exist.

### ISSUE THREAD

**Issue by ryojii** [fluentassertions/fluentassertions.json#38]
Hi and Thank's for the great works you have done.

I Want to check if a propertie is present in a Json and if the value is correct. 
I use this :
` var actual = JToken.Parse(json);
 actual.Should().HaveElement("name").And.Subject.SelectToken("name").Should().HaveValue("Foo");`

When I use another token name in SelectToken() nothing is logged explaining that this token does not exist.

` var actual = JToken.Parse(json);
 actual.Should().HaveElement("name").And.Subject.SelectToken("firstname").Should().HaveValue("Foo");`

I think there should be an exception or a log because the last check `Should().HaveValue("Foo");` does'nt raise any error.

Thanks,
Ryojii

context:
FluentAssertion.Json v5.5.0
FluentAssertion v5.10.3
ide: VS v16.6.2
os: win10

**Comment by dennisdoomen** [comment]
I guess `SelectToken()` is part of `Newtonsoft.Json`? What does it return?

**Comment by ryojii** [comment]
Hi, 
You are right. It retrun  a Newtonsoft.Json.Linq.JToken, or null.

**Comment by dennisdoomen** [comment]
So you're saying that `HaveValue("Foo")` ignores the `null` value?

**Comment by ryojii** [comment]
I'don't think so.  I can not imagine how it could ignore a null value. 
I suppose it crash but log nothing.
I forgot to say that I use AssertionScope.

**Comment by ryojii** [comment]
I finally find a reproducer :
```
        [Fact]
        public void reproducerForIssue38()
        {
            string jsonAsString =
                "{\"name\":\"foo\", \"firstname\":\"bar\"}";
            using (new AssertionScope())
            {
                var json = jsonAsString;
                JToken actual = JToken.Parse(json);
                actual.Should().HaveElement("name").And.Subject.SelectToken("name").Should().HaveValue("bar");
                actual.Should().HaveElement("firstname").And.Subject.SelectToken("surname").Should().HaveValue("bar");
            }
        }
```
This code give this output : 
` Expected JSON property "name" to have value "bar", but found "foo".`

using `surname` in the second line return a null with SelectToken and should raise an exception. 
I'm not sure anymore this is the right place for this ticket ...

**Comment by ryojii** [comment]
I finally find a reproducer :

        [Fact]
        public void reproducerForIssue38()
        {
            string jsonAsString =
                "{\"name\":\"foo\", \"firstname\":\"bar\"}";
            using (new AssertionScope())
            {
                var json = jsonAsString;
                JToken actual = JToken.Parse(json);
                actual.Should().HaveElement("name").And.Subject.SelectToken("name").Should().HaveValue("bar");
                actual.Should().HaveElement("firstname").And.Subject.SelectToken("surname").Should().HaveValue("bar");
            }
        }

This code give this output :
Expected JSON property "name" to have value "bar", but found "foo".

using surname in the second line return a null with SelectToken and should raise an exception.
I'm not sure anymore this is the right place for this ticket ...

**Comment by dennisdoomen** [comment]
If `SelectToken("surname")` returns `null`, then I would expect `Should().HaveValue("bar")` to throw an assertion failure when the `AssertionScope` goes out of scope.

**Comment by dennisdoomen** [comment]
Ah, it actually does, but because of the `using` block, FA actuallys throws two exceptions, but only one is captured by xUnit.
