### ISSUE TITLE
Json Compare with Tolerances

### ISSUE THREAD

**Issue by fractalocity** [fluentassertions/fluentassertions.json#48]
Can you do a Json compare which will take into account tollerances?

settings your tolerances in a json object?

tolerances:
{
  [
    {
      "CarMake": null,
      "Weight": +/- 0.001,
      "Length": +/- 0.02
    }
  ]
}

**Comment by dennisdoomen** [comment]
What do you mean with that?

**Comment by fractalocity** [comment]
This is a better example of what I am trying to accomplish:
https://stackoverflow.com/questions/63378565/c-sharp-json-compare-with-tolerances

**Comment by dennisdoomen** [comment]
Ah, I was afraid that you meant that ;-)

But no, that would require a pretty complicated API.

**Comment by fractalocity** [comment]
:). okay, just checking. Thanks for the response!
