### ISSUE TITLE
Question: Matching .NET object against JSON document

### ISSUE THREAD

**Issue by ishepherd** [fluentassertions/fluentassertions.json#51]
Actual: a strongly-typed object graph from .NET (C#)

Expected: a JSON document in a file

Is it possible to compare these two?

**Comment by dennisdoomen** [comment]
This goes way beyond what you may expect from a library like this, but what you could do is leverage `NewtowSoft.Json`'s ability to deserialize a JSON document into a type defined by an anonymous type, and then use `BeEquivalentTo` to compare that deserialized object with the expected object.

**Comment by ishepherd** [comment]
Thanks Dennis

I guess I wondered if there was some intermediate representation that FluentAssertions/FluentAssertions.Json shared and could compare one from each side.

Just handwaving I guess. :)
