### ISSUE TITLE
Nuget package 4.20 content

### ISSUE THREAD

**Issue by Sbou** [fluentassertions/fluentassertions.json#9]
Hi,

I have an issue to use MsTest v2 Unit test with FluentAssertion.Json because the Nuge package for net45 contains 'Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll' lib.

Is it possible to remove this dll from Nuget package ?

Thanks,

**Comment by dennisdoomen** [comment]
Released as 4.20.1
